### ISSUE TITLE
Solaris by Cosmiq works

### ISSUE THREAD

**Issue by chrieke** [robmarkcole/satellite-image-deep-learning#10]
Great list, have suggested it to multiple people that are looking for DL+Geo ressources. 

Solaris should def. be added here, great tool! DL framework for remote sensing data a bit similar to rastervision but with some unique very vool features! https://github.com/CosmiQ/solaris

On mobile for some time so no PR sorry :)

**Comment by robmarkcole** [comment]
Thanks @chrieke have added it now, cheers!
