### ISSUE TITLE
The README file in this repo has some bad links - [404:NotFound]

### ISSUE THREAD

**Issue by MrCull** [robmarkcole/satellite-image-deep-learning#11]
The README file in this repo has some bad links - [404:NotFound]

The markup version of the readme that is displayed for the main page in this repo contains the following links:
Status code [404:NotFound] - Link: https://www.kaggle.com/robmarkcole/satellite-image-classification (Example notebook)
Status code [404:NotFound] - Link: http://scikit-image.org/docs/dev/auto_examples/transform/plot_register_translation.html?highlight=cross%20correlation (Phase correlation in scikit-image)
Status code [404:NotFound] - Link: https://developers.planet.com/docs/quickstart/getting-started/  (API key)
Status code [404:NotFound] - Link: https://github.com/galiboo/olympus

(The link in the readme’s raw markdown may appear in a different format to the link above)

Theses bad links were found by a tool I very recently created as part of an new experimental hobby project: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
I (a human) verified that this link is broken and have manually logged this Issue (i.e. this Issue has not been created by a bot).
If this has been in any way helpful then please consider giving the above Repo a Star.

**Comment by robmarkcole** [comment]
Thanks @MrCull resolved in https://github.com/robmarkcole/satellite-image-deep-learning/commit/a6dbe97a44284ec4484371115bd99543dea3069b
I created https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder/issues/35
Cheers
