### ISSUE TITLE
More related works

### ISSUE THREAD

**Issue by Z-Zheng** [robmarkcole/satellite-image-deep-learning#20]
**Object Segmentation** Foreground-Aware Relation Network for Geospatial Object Segmentation in High Spatial Resolution Remote Sensing Imagery (https://github.com/Z-Zheng/FarSeg) (CVPR 2020).
**Hyperspectral Image Segmentation** FPGA: Fast Patch-Free Global Learning Framework for Fully End-to-End Hyperspectral Image Classification (https://github.com/Z-Zheng/FreeNet) (TGRS 2020).
**All-Weather Mapping** Deep multisensor learning for missing-modality all-weather mapping  (https://www.sciencedirect.com/science/article/pii/S0924271620303476) (ISRPS P&RS 2021).
**Object Detection**  HyNet: Hyper-scale object detection network framework for multiple spatial resolution remote sensing imagery (https://www.sciencedirect.com/science/article/pii/S0924271620301167) (ISRPS P&RS 2020)

**Comment by robmarkcole** [comment]
Thanks! Do either of these have published code? This is my usual requirement for inclusion

- https://www.sciencedirect.com/science/article/abs/pii/S0924271620303476
- https://www.sciencedirect.com/science/article/abs/pii/S0924271620301167

**Comment by robmarkcole** [comment]
stale
