### ISSUE TITLE
Location of PEARL in readme

### ISSUE THREAD

**Issue by martham93** [robmarkcole/satellite-image-deep-learning#25]
👋 Hi @robmarkcole thanks so much for compiling these resources. Just wanted to let you know that[ PEARL](https://www.landcover.io) is publicly available for free. Could it maybe please be moved from the `useful paid software` section into the `semantic segmentation section`?

**Comment by robmarkcole** [comment]
Hi @martham93 thanks for getting in touch. I've updated the description in https://github.com/robmarkcole/satellite-image-deep-learning/commit/7ca56a9f4785b6a7206dd2b4d7e80a3309d3e8f8 would you mind confirming/rejecting the statement `ML models run locally in the browser`? 
Thanks
