### ISSUE TITLE
SEN12MS Dataset

### ISSUE THREAD

**Issue by system123** [robmarkcole/satellite-image-deep-learning#3]
We have recently released an updated version of the SEN1-2 dataset, it contains the same regions, but we have added all the S2 multispectral bands, All S1 bands as well as corresponding MODIS land cover.

Paper: https://elib.dlr.de/128117/1/SEN12MS_Preprint.pdf
Data: https://mediatum.ub.tum.de/1474000

It is now the largest, manually curated dataset of S1 and S2 products, with corresponding labels for land use/land cover mapping, SAR-optical fusion, segmentation and classification tasks

**Comment by robmarkcole** [comment]
[Updated](https://github.com/robmarkcole/satellite-image-deep-learning/commit/510ce47e307992859fa92f2dc90fa0944d4fa259), many thanks!
