### ISSUE TITLE
New SOTA Methods for Change Detection

### ISSUE THREAD

**Issue by Z-Zheng** [robmarkcole/satellite-image-deep-learning#31]
ICCV21, Change is Everywhere: Single-Temporal Supervised Object Change Detection in Remote Sensing Imagery

RSE21, Building Damage Assessment for Rapid Disaster Response with a Deep Object-based Semantic Change Detection Framework: from natural disasters to man-made disasters

ISPRS P&RS 22, ChangeMask: Deep Multi-task Encoder-Transformer-Decoder Architecture for Semantic Change Detection

**Comment by robmarkcole** [comment]
Thanks, for ChangeMask are you aware of published code?

**Comment by robmarkcole** [comment]
no response
