### ISSUE TITLE
 AMI for rareplanes-yolov5 no longer available on AWS

### ISSUE THREAD

**Issue by AlbTchik** [robmarkcole/satellite-image-deep-learning#45]
Hi robmarkcole,

I was trying to implement the tutorial on YOLOv5 Object Detection for RarePlanes : https://github.com/jeffaudi/rareplanes-yolov5
But I found a bug which make one part of the tutorial no longer useable. It's related with AWS and CosmiQ. 

The problem appear in step 3 of the A. AMI/EC2 part, when trying to find the AMI CosmiQ_YOLO_Planes. Which it was impossible to find. Here you can have a look at my AWS AMI search.

![AMI CosmiQ](https://user-images.githubusercontent.com/90097422/212049733-a4a2c142-6297-434d-8926-e0536dd5a665.png)

After some research I found out that CosmiQ has been closed down since March 2021 : https://medium.com/the-downlinq/closing-time-cosmiq-works-is-closing-down-and-ending-its-leadership-of-spacenet-a53ba239745b
Therfore, all of the AMI they provided have been removed. So this part of the tutorial is not longer useable.

However, I could still download the RarePlanes dataset from the s3Bucket to work locally and accomplish the second part : B. On your own GPUs.

Thanks for your help with this wonderful repo,

Alban Tchikladzé

**Comment by robmarkcole** [comment]
Hi @AlbTchik thank you for your message. I also noticed today that CosmiQ resources are no longer available, and have updated the links in this repo. I will also reference this issue. Many thanks. Btw if you are looking for yolov8 I have published https://github.com/robmarkcole/kaggle-ships-in-Google-Earth
