### ISSUE TITLE
Collapsible markdowns

### ISSUE THREAD

**Issue by GOItPadma** [robmarkcole/satellite-image-deep-learning#46]
Dear Sir,
According to our last conversation, you were looking for a collapsible markdown format for the readme file. A format is mentioned in the [github doc](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections). By using the `<details>` tag, it is possible to create dropdown contents. I have tried to change the font styles within the `<summary>` tag, but did not work.

**Comment by robmarkcole** [comment]
That appears to work well!

![image](https://user-images.githubusercontent.com/11855322/213417200-6bccbca8-fbf8-4691-a978-bb19b8d2932f.png)
